// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	database "github.com/KarnerTh/mermerd/database"

	io "io"

	mock "github.com/stretchr/testify/mock"
)

// Diagram is an autogenerated mock type for the Diagram type
type Diagram struct {
	mock.Mock
}

// Create provides a mock function with given fields: wr, result
func (_m *Diagram) Create(wr io.Writer, result *database.Result) error {
	ret := _m.Called(wr, result)

	var r0 error
	if rf, ok := ret.Get(0).(func(io.Writer, *database.Result) error); ok {
		r0 = rf(wr, result)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDiagram creates a new instance of Diagram. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDiagram(t interface {
	mock.TestingT
	Cleanup(func())
}) *Diagram {
	mock := &Diagram{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
